// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table animals {
  id integer [primary key]
  animal_type_id integer [ref: > animal_types.id]
  owner_id integer [ref: > owners.id]
  farm_id integer [ref: > farm.id]
  id_status integer [ref: > status.id]
  identification varchar[50] [note: 'Numero do Brinco ou nome do animal']
  identification_color varchar[50] [note: 'Cor da identificação se existir - ex: vermelho, azul']
  animal_birth timestamp [note: 'Data de nascimento do animal']
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
  deleted_at timestamp [default: `now()`]
}

Table animal_types {
  id integer [primary key]
  tipo varchar[50] [note: 'Bovino, Caprino, Equino, Suíno, Ovino']
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table animal_vaccines {
  id integer [primary key]
  animal_id integer [ref: > animals.id]
  vaccine_id integer [ref: > vaccines.id]
  vaccine_date timestamp
}

Table animal_medications {
  id integer [primary key]
  animal_id integer [ref: > animals.id]
  medication_id integer [ref: > medication.id]
  medication_data timestamp
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table farm {
  id integer [primary key]
  farm varchar[50] [note: 'Nome da farm']
  logo varchar[100] [note: 'Logo da farm']
  descricao text [note: 'Descrição da farm']
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table photos
  id integer [primary key]
  animal_id integer [ref: > animals.id]
  file varchar[100]
  description varchar[250]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
  deleted_at timestamp [default: `now()`]
}

Table medication {
  id integer [primary key]
  medication varchar[250]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table owners {
  id integer [primary key]
  owner varchar[150]
  brinco_cor varchar[50]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table status {
  id integer [primary key]
  status varchar[50]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table vaccines {
  id integer [primary key]
  vaccine varchar[150]
  vaccine_data timestamp
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}
