// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table animals {
  id integer [primary key]
  animal_type_id integer [ref: > animal_type.id]
  id_proprietario integer [ref: > proprietario.id]
  id_fazenda integer [ref: > fazenda.id]
  id_status integer [ref: > status.id]
  identifacao varchar[50] [note: 'Numero do Brinco ou nome do animal']
  identicacao_cor varchar[50] [note: 'Cor da identificação se existir - ex: vermelho, azul']
  nascimento_animal timestamp [note: 'Data de nascimento do animal']
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
  deleted_at timestamp [default: `now()`]
}

Table animal_type {
  id integer [primary key]
  tipo varchar[50] [note: 'Bovino, Caprino, Equino, Suíno, Ovino']
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table animal_vaccine {
  id integer [primary key]
  id_animal integer [ref: > animal.id]
  id_vacinacao integer [ref: > vacinacao.id]
  data_vacinacao timestamp
}

Table animal_medicacao {
  id integer [primary key]
  id_animal integer [ref: > animal.id]
  id_medicacao integer [ref: > medicacao.id]
  data_medicacao timestamp
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table fazenda {
  id integer [primary key]
  fazenda varchar[50] [note: 'Nome da fazenda']
  logo varchar[100] [note: 'Logo da fazenda']
  descricao text [note: 'Descrição da fazenda']
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table foto {
  id integer [primary key]
  id_animal integer [ref: > animal.id]
  arquivo varchar[100]
  descricao varchar[250]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
  deleted_at timestamp [default: `now()`]
}

Table medicacao {
  id integer [primary key]
  medicacao varchar[250]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table proprietario {
  id integer [primary key]
  proprietario varchar[150]
  brinco_cor varchar[50]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table status {
  id integer [primary key]
  status varchar[50]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table vacinacao {
  id integer [primary key]
  vacina varchar[150]
  data_vacinacao timestamp
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}
